config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :notes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  root "notes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :user

  encrypts :body

  validates :body, presence: true, length: { maximum: 1_000_000_000 }

  README = File.read(Rails.root.join("README.md"))

  # @return [String] cached README markdown text
  def self.readme
    README
  end

  # @return [String] markdown first line of note
  def title
    return "" if body.blank?
    body.strip.split("\n").first
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable,
  # :timeoutable,
  # :omniauthable
  # :registerable
  devise :database_authenticatable,
         :lockable,
         :trackable,
         :recoverable,
         :rememberable,
         :validatable

  has_many :notes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern

  # Changes to the importmap will invalidate the etag for HTML responses
  stale_when_importmap_changes
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :authenticate_user!, except: %i[ index ]
  before_action :set_note, only: %i[ show edit update destroy ]

  # GET /notes
  def index
    @notes = []
    flash.now.alert = "No users in database. Please create a user from console." if User.count == 0

    if user_signed_in?
      @notes = Note.where(user: current_user).order(updated_at: :desc)
    end
  end

  # GET /notes/1
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  def create
    @note = Note.new(note_params.merge({ user: current_user }))

    if @note.save
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to @note, notice: "Note was successfully created." }
      end
    else
      render :new, status: :unprocessable_content
    end
  end

  # PATCH/PUT /notes/1
  def update
    if @note.update(note_params)
      respond_to do |format|
        format.turbo_stream
        format.html { redirect_to notes_path, notice: "Note was successfully updated.", status: :see_other }
      end
    else
      render :edit, status: :unprocessable_content
    end
  end

  # DELETE /notes/1
  def destroy
    @note.destroy!
    redirect_to notes_path, notice: "Note was permanently deleted."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find_by(id: params.expect(:id), user: current_user)
    end

    # Only allow a list of trusted parameters through.
    def note_params
      params.expect(note: [ :body ])
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  MARKDOWN = Redcarpet::Markdown.new(
    Redcarpet::Render::HTML.new(
      filter_html: true,
      no_images: false,
      no_links: false,
      safe_links_only: true,
      hard_wrap: true
    ),
    autolink: true,
    tables: true,
    strikethrough: true,
    superscript: true,
    no_intra_emphasis: true,
    fenced_code_blocks: true
  )
  TIME_FORMAT = "%r %x"

  # @param s [String]
  def markdown(s)
    sanitize(
      MARKDOWN.render(s),
      tags: %w[p br strong em ul ol li h1 h2 h3 h4 h5 h6 code pre blockquote table thead tbody tr th td a hr],
      attributes: { "a" => [ "href" ] }
    )
  end

  # @param d [DateTime, #to_datetime, nil]
  # @return [String]
  # @raises [StandardError]
  def time_format(d)
    if d.nil?
      "N/A"
    elsif d.is_a? DateTime
      d.strftime(TIME_FORMAT)
    elsif d.respond_to? :to_datetime
      time_format(d.to_datetime)
    else
      raise StandardError, "Cannot convert #{d} into time format"
    end
  end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Notes" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <meta name="application-name" content="Notes">
    <meta name="mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <%# Enable PWA manifest for installable apps (make sure to enable in config/routes.rb too!) %>
    <%= tag.link rel: "manifest", href: pwa_manifest_path(format: :json) %>

    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">

    <%# Includes all stylesheet files in app/assets/stylesheets %>
    <%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <nav>
      <%= link_to "Notes App", root_url %> |
      <% if user_signed_in? %>
        <%= link_to "Sign Out", destroy_user_session_path, data: { turbo_method: :delete } %> |
        Signed in as <%= current_user.email %>
      <% else %>
        <%= link_to "Sign In", new_user_session_path %>
      <% end %>
    </nav>
    <turbo-frame id="alert">
      <% if flash[:notice] %>
          <span style="color:green"><%= flash[:notice] %></span>
      <% end %>
      <% if flash[:alert] %>
          <span style="color:red"><%= flash[:alert] %></span>
      <% end %>
    </turbo-frame>
    <%= yield %>
  </body>
</html>

app/views/notes/_form.html.erb
<%= form_with(model: note, data: { turbo_frame: note.new_record? ? "new_note" : dom_id(note) }) do |form| %>
  <% if note.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
        <% note.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :body, style: "display: none" %>
    <%= form.text_area :body, rows: 4, placeholder: "Write a new note in Markdown", required: true %>
  </div>

  <div>
    <%= form.submit "Save" %>
    <% unless note.new_record? %>
      <%= link_to "Back", notes_path, data: { turbo_frame: "_top" } %>
    <% end %>
  </div>
<% end %>

app/views/notes/_note.html.erb
<div id="<%= dom_id note %>">
  <%= link_to edit_note_path(note), data: { turbo_frame: "_top" } do %>
    <%= markdown note.title %>
  <% end %>
</div>

app/views/notes/create.turbo_stream.erb
<%= turbo_stream.prepend "notes" do %>
  <%= turbo_frame_tag dom_id(@note) do %>
    <%= render @note %>
  <% end %>
<% end %>

<%= turbo_stream.replace "new_note" do %>
  <%= turbo_frame_tag "new_note" do %>
    <%= render "form", note: Note.new %>
  <% end %>
<% end %>

app/views/notes/edit.html.erb
<% content_for :title do %>
  Editing #<%= @note.id %> | Notes App
<% end %>

<h1>Editing Note #<%= @note.id %></h1>

<p>
  <small>
    Created <%= time_ago_in_words(@note.created_at) %> ago.
    <% if @note.updated_at - @note.created_at > 1.minute %>
      Last saved <%= time_ago_in_words(@note.updated_at) %> ago.
    <% end %>
  </small>
</p>

<%= turbo_frame_tag dom_id(@note) do %>
  <%= render "form", note: @note %>
<% end %>

<div>
  <%= button_to "Fullscreen", @note, method: :get %>
  <%= button_to "Delete", @note, method: :delete, data: { turbo_frame: "_top" } %>
</div>

app/views/notes/index.html.erb
<main>
<% if user_signed_in? %>
  <header>
    <h1>Notes</h1>
  </header>

  <section>
    <%= turbo_frame_tag "new_note" do %>
      <%= render "form", note: Note.new %>
    <% end %>
  </section>

  <section>
    <p><b>Your Notes</b></p>
    <%= turbo_stream_from "notes" %>
    <div id="notes">
      <% if @notes.any? %>
        <% @notes.each do |note| %>
          <%= turbo_frame_tag dom_id(note) do %>
            <%= render note %>
          <% end %>
        <% end %>
      <% else %>
        <p>No notes yet. Create your first note above!</p>
      <% end %>
    </div>
  </section>
<% else %>
  <%= markdown Note.readme %>
<% end %>
</main>

app/views/notes/new.html.erb
<% content_for :title, "New note" %>

<h1>New note</h1>

<%= render "form", note: @note %>

<br>

<div>
  <%= link_to "Back to notes", notes_path %>
</div>

app/views/notes/show.html.erb
<% content_for :title do %>
  <%= @note.title %>
<% end %>

<p>
  Created <%= time_format @note.created_at %>.
  <% if @note.updated_at > @note.created_at %>
    Last edited <%= time_format @note.updated_at %>
  <% end %>
</p>

<div id="<%= dom_id @note %>">
  <%= markdown @note.body %>
</div>

app/views/notes/update.turbo_stream.erb
<%= turbo_stream.replace "alert" do %>
  <%= turbo_frame_tag "alert" do %>
    <span style="color: green">Note saved successfully <%= @note.updated_at.strftime("%r %Z") %>.</span>
  <% end %>
<% end %>

<%= turbo_stream.replace dom_id(@note) do %>
  <%= turbo_frame_tag dom_id(@note) do %>
    <%= render "form", note: @note %>
  <% end %>
<% end %>